import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { STORAGE_KEYS } from '@/constants/api.constants';

/**
 * 支持的语言类型
 */
export type Language = 'zh' | 'en';

/**
 * 语言Store状态接口
 */
interface ILanguageState {
  /** 当前语言 */
  language: Language;
  
  /** 设置语言 */
  setLanguage: (lang: Language) => void;
  
  /** 切换语言 */
  toggleLanguage: () => void;
}

/**
 * 多语言Store
 * 管理界面语言设置并持久化到localStorage
 */
export const useLanguageStore = create<ILanguageState>()(
  persist(
    (set, get) => ({
      // 默认中文
      language: 'zh',

      /**
       * 设置语言
       * @param lang - 语言代码
       */
      setLanguage: (lang) => {
        set({ language: lang });
      },

      /**
       * 切换语言（中英文切换）
       */
      toggleLanguage: () => {
        const { language } = get();
        set({ language: language === 'zh' ? 'en' : 'zh' });
      },
    }),
    {
      name: STORAGE_KEYS.LANGUAGE,
    }
  )
);

/**
 * 多语言文案配置
 */
export const translations = {
  zh: {
    // 导航栏
    nav: {
      goToHomepage: '去充值',
      apiAccess: 'API接入',
      console: '控制台',
      history: '历史记录',
    },
    // 首页标题
    hero: {
      title: 'Cetcor.AI',
      version: '',
      subtitle: '体验图片生成，让创意摇摆',
    },
    // 表单
    form: {
      promptPlaceholder: '描述你想要生成的图片...',
      promptLabel: '提示词',
      modeLabel: '自动组图模式',
      modeDescription: '描述想生成的图片',
      sizeLabel: '生成组图',
      maxImagesLabel: '上限15张',
      maxImages: '最多生成',
      maxImagesUnit: '张',
      generateButton: '生成',
      generating: '生成中...',
    },
    // 图片画廊
    gallery: {
      title: '生成结果',
      download: '下载',
      copyPrompt: '复制提示词',
      noResults: '暂无生成结果',
    },
    // 历史记录
    history: {
      title: '历史记录',
      empty: '暂无历史记录',
      clear: '清空',
      close: '关闭',
      generatedAt: '生成于',
    },
    // 错误提示
    error: {
      networkError: '网络错误，请稍后重试',
      apiError: 'API调用失败',
      validationError: '输入验证失败',
    },
    // 底部说明
    footer: {
      disclaimer: '试用体验内容均由人工智能模型生成，不代表平台立场观点明示或暗示试验阶段政策',
    },
  },
  en: {
    // Navigation
    nav: {
      goToHomepage: 'Top Up',
      apiAccess: 'API Access',
      console: 'Console',
      history: 'History',
    },
    // Hero
    hero: {
      title: 'Cetcor.AI',
      version: '',
      subtitle: 'Experience Image Generation, Let Creativity Swing',
    },
    // Form
    form: {
      promptPlaceholder: 'Describe the image you want to generate...',
      promptLabel: 'Prompt',
      modeLabel: 'Auto Group Mode',
      modeDescription: 'Describe images to generate',
      sizeLabel: 'Generate Group',
      maxImagesLabel: 'Max 15',
      maxImages: 'Max Images',
      maxImagesUnit: '',
      generateButton: 'Generate',
      generating: 'Generating...',
    },
    // Gallery
    gallery: {
      title: 'Results',
      download: 'Download',
      copyPrompt: 'Copy Prompt',
      noResults: 'No results yet',
    },
    // History
    history: {
      title: 'History',
      empty: 'No history yet',
      clear: 'Clear',
      close: 'Close',
      generatedAt: 'Generated at',
    },
    // Error
    error: {
      networkError: 'Network error, please try again later',
      apiError: 'API call failed',
      validationError: 'Validation failed',
    },
    // Footer
    footer: {
      disclaimer: 'Trial content is generated by AI models and does not represent the platform\'s stance or views. Trial phase policy applies.',
    },
  },
};

/**
 * 获取翻译文案的Hook
 */
export function useTranslation() {
  const language = useLanguageStore((state) => state.language);
  return translations[language];
}

